# Generated by Django 4.2 on 2023-05-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SliderImages')),
                ('title', models.CharField(max_length=40)),
                ('body', models.CharField(blank=True, max_length=40, null=True)),
                ('Promontion', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_c',)},
        ),
    ]
