# Generated by Django 4.2 on 2023-05-09 22:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='SliderImages'),
        ),
    ]
