# Generated by Django 4.2 on 2023-05-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_cartitem_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='time',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='time',
        ),
    ]
